[build]
builder = "dockerfile"
watchPatterns = ["src/**", "migrations/**", "configuration/**"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
