application:
  port: 8000
database:
  host: 127.0.0.1
  port: 5432
  username: "postgres"
  password: "postgres"
  name: "newsletter_dev"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
